server:
  port: 1010

spring:
  application:
    name: hello-service

eureka:
  client:
    service-url:
      #defaultZone: http://admin:123456@localhost:1000/eureka
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
    healthcheck:
      enabled: true