server:
  port: 1020

spring:
  application:
    name: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:1000/eureka
    healthcheck:
      enabled: true

hello-service:
  ribbon:
    MaxAutoRetries: 2

feign:
  compression:
    request:
      enabled: true
    response:
      enables: true

logging:
  level:
    com:
      mhts:
        springcloud:
          service:
            HelloService: DEBUG